FROM node:alpine

WORKDIR /backend/calendly

COPY package*.json ./

COPY tsconfig.json ./

COPY prisma.config.ts ./

RUN pnpm install

COPY src/ ./src/

COPY prisma/ ./prisma/

RUN pnpm prisma generate

# Executes At image build time
RUN pnpm run build   

# Executes At container start time
CMD ["pnpm", "run", "dev"]